version: '3'
services:
  web:
    image: webdevops/apache
    ports:
      - 8080:80
    volumes:
      - .:/usr/local/apache2/htdocs
    environment:
      WEB_DOCUMENT_ROOT: /usr/local/apache2/htdocs/web
